Do not import lodash
3YOURMIND/kotti pull request #573
Opened 2021-12-17 04:40 UTC by HansAuger

Removes all instances of imports that pull all of lodash into our package.

```ts
import { someUtil } from 'lodash' 
```

I also removed it from documentation which I know is not necessary, but I thought is was better to be consistent across the app.

2021-12-17 07:23 UTC, FlorianWendelborn commented
Did you test if this actually decreases the bundle size?

2021-12-17 07:24 UTC, FlorianWendelborn requested changes

2021-12-17 07:24 UTC, FlorianWendelborn commented on packages/kotti-ui/source/kotti-user-menu/KtUserMenu.vue
> +				KottiUserMenu.propsSchema.shape.sections.safeParse(props.sections),
Bug

2021-12-23 03:48 UTC, HansAuger commented
@FlorianWendelborn True.  I did run `build:kotti:esm/build:kotti:cjs` and looked at the resulting bundle and actually saw a small increase. So I guess  this is a failja

2022-05-12 05:18 UTC, closed without merging