revert(#661): partially: `.form-radio` class still in use
3YOURMIND/kotti pull request #673
Opened 2022-10-13 13:32 UTC by carsoli

bring back `.form-radio` deleted in a tech debt cleanup in #661. It is still in use by our main user-app and will follow in its own deletion, before the next major release.

2022-10-13 16:36 UTC, FlorianWendelborn commented
I’m voting in favor of closing this PR and moving the code over to yoda instead. No need to re-add technical debt back to kotti if it doesn’t matter where it’s handled.

2022-10-13 16:36 UTC, FlorianWendelborn requested changes
I’m voting in favor of closing this PR and moving the code over to yoda instead. No need to re-add technical debt back to kotti if it doesn’t matter where it’s handled.

2022-10-14 08:52 UTC, carsoli commented
@FlorianWendelborn good point

2022-10-14 08:53 UTC, carsoli commented on packages/kotti-ui/source/kotti-style/forms/_toggles.scss
> +.form-radio {
You're right. I just brought back the old file entirely then removed the dead classes, and now that I did, they became mergeable. I'll merge and take them to yoda tbh

2022-10-18 02:14 UTC, FlorianWendelborn commented on packages/kotti-ui/source/kotti-style/forms/_toggles.scss
> +		top: ($control-size-sm - $control-icon-size) / 2;
@carsoli can you maybe check if some of those SCSS variables are dead now that the classes are gone?

2022-10-19 13:32 UTC, closed without merging