feat(yoco): add new icons to Yoco
3YOURMIND/kotti pull request #961
Opened 2024-07-09 09:55 UTC by santiagoballadares

Add icons:
- attention
- circle_magnifying_glass
- circle_minus
- magnifying_glass

- bump version to 2.6.1

2024-07-09 14:38 UTC, Isokaeder requested changes
IMO needs some small improvements.

Also consider making this a `2.7.0` release, since it adds new features.

2024-07-09 14:38 UTC, Isokaeder commented on packages/yoco/svg/magnifying_glass.svg
We already have an icon `search` that depicts a magnifying glass, this seems superfluous.

2024-07-09 14:38 UTC, Isokaeder commented on packages/yoco/svg/circle_magnifying_glass.svg
- Should be called `circle_search`
- line width of "inner" aka the search/magnifying glass should be slightly smaller, looks weird next to other circle icons. See for example icon `circle_question`

2024-07-09 15:38 UTC, closed without merging

2024-07-11 13:36 UTC, santiagoballadares commented
Closed in favor of https://github.com/3YOURMIND/kotti/pull/964